# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.cache/wt [current_project]
set_property parent.project_path /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths {
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/Volume_Pregain
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/SoC_Design/HDL/Audio_Mixer
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/pmod_controller_1.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/SoC_Design/IPs/Audio_Mixer
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/SoC_Design/IPs/OLED/ZedBoard_OLED_1.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/axi_to_audio_interface_1.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/ip_repo_vivado
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/audio_to_axi_interface_1.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/axi_to_audio_interface_1.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/zedboard_audio
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/audio_to_axi_interface_2.0
  /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/ip-repo/axi_to_audio_interface_2.0
} [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
read_ip -quiet /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cantavi_streamer_project_axi_to_audio_interfa_1_2 -part xc7z020clg484-1 -mode out_of_context

rename_ref -prefix_all cantavi_streamer_project_axi_to_audio_interfa_1_2_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cantavi_streamer_project_axi_to_audio_interfa_1_2.dcp
create_report "cantavi_streamer_project_axi_to_audio_interfa_1_2_synth_1_synth_report_utilization_0" "report_utilization -file cantavi_streamer_project_axi_to_audio_interfa_1_2_utilization_synth.rpt -pb cantavi_streamer_project_axi_to_audio_interfa_1_2_utilization_synth.pb"

if { [catch {
  file copy -force /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.runs/cantavi_streamer_project_axi_to_audio_interfa_1_2_synth_1/cantavi_streamer_project_axi_to_audio_interfa_1_2.dcp /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.ip_user_files/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2]} {
  catch { 
    file copy -force /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_stub.v /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.ip_user_files/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2
  }
}

if {[file isdir /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.ip_user_files/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2]} {
  catch { 
    file copy -force /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.srcs/sources_1/bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2/cantavi_streamer_project_axi_to_audio_interfa_1_2_stub.vhdl /home/thanx/HDL-Workspace/Xilinx_SDK_Workspace/MyAudio/CantaviStreamer6/vivado/cantavi_streamer_project.ip_user_files/ip/cantavi_streamer_project_axi_to_audio_interfa_1_2
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
