# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: constraints/zed_audio.xdc

# Block Designs: bd/cantavi_streamer_project/cantavi_streamer_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project || ORIG_REF_NAME==cantavi_streamer_project} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_processing_system7_0_0/cantavi_streamer_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_processing_system7_0_0 || ORIG_REF_NAME==cantavi_streamer_project_processing_system7_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_ps7_0_axi_periph_0/cantavi_streamer_project_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_ps7_0_axi_periph_0 || ORIG_REF_NAME==cantavi_streamer_project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_rst_ps7_0_100M_0/cantavi_streamer_project_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_FILTER_IIR_0_0/cantavi_streamer_project_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_FILTER_IIR_0_0 || ORIG_REF_NAME==cantavi_streamer_project_FILTER_IIR_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_Volume_Pregain_0_0/cantavi_streamer_project_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_Volume_Pregain_0_0 || ORIG_REF_NAME==cantavi_streamer_project_Volume_Pregain_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_xlconcat_0_0/cantavi_streamer_project_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_xlconcat_0_0 || ORIG_REF_NAME==cantavi_streamer_project_xlconcat_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_mixer_0_0/cantavi_streamer_project_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_mixer_0_0 || ORIG_REF_NAME==cantavi_streamer_project_mixer_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_ZedboardOLED_0_0/cantavi_streamer_project_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_ZedboardOLED_0_0 || ORIG_REF_NAME==cantavi_streamer_project_ZedboardOLED_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_FILTER_IIR_1_0/cantavi_streamer_project_FILTER_IIR_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_FILTER_IIR_1_0 || ORIG_REF_NAME==cantavi_streamer_project_FILTER_IIR_1_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_Volume_Pregain_1_1/cantavi_streamer_project_Volume_Pregain_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_Volume_Pregain_1_1 || ORIG_REF_NAME==cantavi_streamer_project_Volume_Pregain_1_1} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_1_0/cantavi_streamer_project_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_1_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_pmod_controller_0_1/cantavi_streamer_project_pmod_controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_pmod_controller_0_1 || ORIG_REF_NAME==cantavi_streamer_project_pmod_controller_0_1} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_2_0/cantavi_streamer_project_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_2_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_2_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_0_2/cantavi_streamer_project_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_0_2 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_0_2} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_xbar_0/cantavi_streamer_project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_xbar_0 || ORIG_REF_NAME==cantavi_streamer_project_xbar_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_user_org_plc_seq_ip_0_0/cantavi_streamer_project_user_org_plc_seq_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_user_org_plc_seq_ip_0_0 || ORIG_REF_NAME==cantavi_streamer_project_user_org_plc_seq_ip_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_adau1761_controller_0_0/cantavi_streamer_project_adau1761_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_adau1761_controller_0_0 || ORIG_REF_NAME==cantavi_streamer_project_adau1761_controller_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_i2s_receiver_0_0/cantavi_streamer_project_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_i2s_receiver_0_0 || ORIG_REF_NAME==cantavi_streamer_project_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_i2s_transmitter_0_0/cantavi_streamer_project_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_i2s_transmitter_0_0 || ORIG_REF_NAME==cantavi_streamer_project_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_clk_wiz_0_0/cantavi_streamer_project_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_clk_wiz_0_0 || ORIG_REF_NAME==cantavi_streamer_project_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_time_sync_block_0_0/cantavi_streamer_project_time_sync_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_time_sync_block_0_0 || ORIG_REF_NAME==cantavi_streamer_project_time_sync_block_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_eth_to_audio_plc_com_0_0/cantavi_streamer_project_eth_to_audio_plc_com_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_eth_to_audio_plc_com_0_0 || ORIG_REF_NAME==cantavi_streamer_project_eth_to_audio_plc_com_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_mixer_0_1/cantavi_streamer_project_mixer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_mixer_0_1 || ORIG_REF_NAME==cantavi_streamer_project_mixer_0_1} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_audio_fader_0_0/cantavi_streamer_project_audio_fader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_audio_fader_0_0 || ORIG_REF_NAME==cantavi_streamer_project_audio_fader_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_audio_fader_0_1/cantavi_streamer_project_audio_fader_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_audio_fader_0_1 || ORIG_REF_NAME==cantavi_streamer_project_audio_fader_0_1} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_org_audio2eth_interl_0_0/cantavi_streamer_project_org_audio2eth_interl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_org_audio2eth_interl_0_0 || ORIG_REF_NAME==cantavi_streamer_project_org_audio2eth_interl_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_user_cross_layer_swi_0_0/cantavi_streamer_project_user_cross_layer_swi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_user_cross_layer_swi_0_0 || ORIG_REF_NAME==cantavi_streamer_project_user_cross_layer_swi_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_eth_udp_axi_arp_stack_0_0/cantavi_streamer_project_eth_udp_axi_arp_stack_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_eth_udp_axi_arp_stack_0_0 || ORIG_REF_NAME==cantavi_streamer_project_eth_udp_axi_arp_stack_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_synchronizer_0_0/cantavi_streamer_project_synchronizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_synchronizer_0_0 || ORIG_REF_NAME==cantavi_streamer_project_synchronizer_0_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_synchronizer_3_0/cantavi_streamer_project_synchronizer_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_synchronizer_3_0 || ORIG_REF_NAME==cantavi_streamer_project_synchronizer_3_0} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_synchronizer_3_1/cantavi_streamer_project_synchronizer_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_synchronizer_3_1 || ORIG_REF_NAME==cantavi_streamer_project_synchronizer_3_1} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_synchronizer_3_2/cantavi_streamer_project_synchronizer_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_synchronizer_3_2 || ORIG_REF_NAME==cantavi_streamer_project_synchronizer_3_2} -quiet] -quiet

# IP: bd/cantavi_streamer_project/ip/cantavi_streamer_project_auto_pc_0/cantavi_streamer_project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_auto_pc_0 || ORIG_REF_NAME==cantavi_streamer_project_auto_pc_0} -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_processing_system7_0_0/cantavi_streamer_project_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_processing_system7_0_0 || ORIG_REF_NAME==cantavi_streamer_project_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_rst_ps7_0_100M_0/cantavi_streamer_project_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_rst_ps7_0_100M_0/cantavi_streamer_project_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==cantavi_streamer_project_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_1_0/cantavi_streamer_project_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_1_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_1_0/cantavi_streamer_project_axi_gpio_1_0_ooc.xdc

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_1_0/cantavi_streamer_project_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_1_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_2_0/cantavi_streamer_project_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_2_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_2_0/cantavi_streamer_project_axi_gpio_2_0_ooc.xdc

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_2_0/cantavi_streamer_project_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_2_0 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_0_2/cantavi_streamer_project_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_0_2 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_0_2/cantavi_streamer_project_axi_gpio_0_2_ooc.xdc

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_axi_gpio_0_2/cantavi_streamer_project_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_axi_gpio_0_2 || ORIG_REF_NAME==cantavi_streamer_project_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_clk_wiz_0_0/cantavi_streamer_project_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_clk_wiz_0_0 || ORIG_REF_NAME==cantavi_streamer_project_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_clk_wiz_0_0/cantavi_streamer_project_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cantavi_streamer_project_clk_wiz_0_0 || ORIG_REF_NAME==cantavi_streamer_project_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_clk_wiz_0_0/cantavi_streamer_project_clk_wiz_0_0_ooc.xdc

# XDC: bd/cantavi_streamer_project/ip/cantavi_streamer_project_auto_pc_0/cantavi_streamer_project_auto_pc_0_ooc.xdc

# XDC: bd/cantavi_streamer_project/cantavi_streamer_project_ooc.xdc
